### PR TITLE
Feature/flashcard list

### PR DESCRIPTION
**Pull request by P-Oliomonte**

### CODE REVIEW

**Comment by Rahaf91** [comment]
Well structured!  I think everything is okay. I wanted to mention using the <h1> in the component as Andrea said, but Elisabeth has already updated it....Great work.

**Review by Rahaf91 — COMMENTED** [review]
Well structured! I think everything is okay. I wanted to mention using the `<h1> `in the component as Andrea said, but Elisabeth has already updated it. 
Great work :)

**Comment by eneben** [comment]
> Well structured! I think everything is okay. I wanted to mention using the
> 
> # in the component as Andrea said, but Elisabeth has already updated it.
> Great work :)

**Comment by eneben** [comment]
> > Well structured! I think everything is okay. I wanted to mention using the
> > # in the component as Andrea said, but Elisabeth has already updated it.
> > Great work :)

**Comment by eneben** [comment]
> > > Well structured! I think everything is okay. I wanted to mention using the
> > > # in the component as Andrea said, but Elisabeth has already updated it.
> > > Great work :)


Thank you :blush:

**Pull request merged**
